name: 'Git Commit Lit!!!!'
description: 'Random Git Commits that makes your Github Contribution Graph lit!'
inputs:
  lower-bound:  # id of input
    description: 'lower bound of number of commits per day'
    required: true
    default: '0'
  upper-bound:  # id of input
    description: 'upper bound of number of commits per day'
    required: true
    default: '7' 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lower-bound }}
    - ${{ inputs.upper-bound }}
